import fs from 'node:fs';
import assert from 'node:assert/strict';
const files = ['dashboard','venues','exhibitions','homepage','media','authors','users','archive'].map((name) => fs.readFileSync(new URL(`../admin/views/${name}.js`, import.meta.url), 'utf8'));
const joined = files.join('\n');
for (const term of ['SAVE','Publish','Venue','Exhibition','Media','Authors','Users','Archive']) assert.ok(joined.toLowerCase().includes(term.toLowerCase()), term);
assert.ok(joined.includes('setAuthors'));
assert.ok(joined.includes('runJob'));
assert.equal(joined.includes('Venue roles JSON'), false);
assert.equal(joined.includes('Cover media UUID'), false);
console.log('Admin Static tests passed.');
