import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const gallery = fs.readFileSync(new URL('../gallery/index.html', import.meta.url), 'utf8');
const admin = fs.readFileSync(new URL('../admin/index.html', import.meta.url), 'utf8');
const publicJs = fs.readFileSync(new URL('../src/public-site/public-site.js', import.meta.url), 'utf8');
assert.equal(root.includes('renderCanvas'), false);
assert.equal(root.includes('babylon.js'), false);
assert.equal(gallery.includes('renderCanvas'), true);
assert.equal(admin.includes('adminApp'), true);
assert.equal(publicJs.includes('get_public_site_content'), true);
assert.equal(publicJs.includes('list_public_exhibition_cards'), true);
console.log('Public Site Separation tests passed.');
