import { el, button, field, textInput, selectInput, jsonTextarea, parseJsonTextarea } from "../core/dom.js";
import { pageHead, panel, errorBlock, actionButton } from "./shared.js";
import { createDefaultHomepage, createDefaultSiteSettings, normalizeHomepage, normalizeSiteSettings, validateHomepage } from "../../src/platform/schemas/cms-schemas.js";

const LABELS = { hero:"Hero", exhibition_collection:"Lista / karuzela wystaw", about:"O galerii", partners:"Partnerzy", contact:"Kontakt", footer:"Stopka" };
const clone = (value) => typeof structuredClone === "function" ? structuredClone(value) : JSON.parse(JSON.stringify(value));
const setContent = (section,key,value) => { section.content ||= {}; section.content[key]=value; };
function collectMediaReferences(value,path="root",output=[]) {
  if (Array.isArray(value)) { value.forEach((item,index)=>collectMediaReferences(item,`${path}.${index}`,output)); return output; }
  if (!value || typeof value!=="object") return output;
  for (const [key,item] of Object.entries(value)) {
    const nextPath=`${path}.${key}`;
    if (/MediaId$/i.test(key) && typeof item==="string" && item) output.push({mediaId:item,usageRole:nextPath});
    else if (/MediaIds$/i.test(key) && Array.isArray(item)) item.filter(Boolean).forEach((mediaId,index)=>output.push({mediaId,usageRole:`${nextPath}.${index}`}));
    else collectMediaReferences(item,nextPath,output);
  }
  return output;
}
async function attachSiteMedia(ctx,key,value) {
  const unique=new Map(collectMediaReferences(value).map(item=>[`${item.mediaId}:${item.usageRole}`,item]));
  for (const item of unique.values()) await ctx.repos.media.attachExisting(item.mediaId,{ownerType:"site",ownerId:"site",entityType:"site-content",entityId:key,usageRole:item.usageRole});
}
function inputRow(label,value,onInput,options={}) { const input=textInput(options.name||"field",value??"",{ multiline:options.multiline,type:options.type||"text",class:options.full?"full":"",attrs:options.attrs||{} }); input.addEventListener("input",()=>onInput(options.type==="number"?Number(input.value||0):input.value)); return field(label,input); }
function mediaChoices(media){return [{value:"",label:"— Brak —"},...(media||[]).map(item=>({value:item.id,label:`${item.metadata?.title||item.media_type||"media"} · ${String(item.id).slice(0,8)}`}))];}
function mediaField(ctx,state,media,label,key,context={}) {
  const select=selectInput(key,mediaChoices(media),state[key]||""); select.addEventListener("change",()=>state[key]=select.value||null);
  const file=el("input",{type:"file",attrs:{accept:context.accept||"image/*,.svg,video/*"}}); const upload=button("Wgraj",{class:"small",onClick:async()=>{if(!file.files?.[0])return ctx.shell.toast("Wybierz plik.","error");upload.disabled=true;try{const result=await ctx.repos.media.uploadSiteFile(file.files[0],{entityType:context.entityType||"homepage",entityId:context.entityId||"homepage",category:context.category||"homepage",usageRole:context.usageRole||key,mediaType:context.mediaType||"image",metadata:{title:label}});const id=result.mediaId||result.media_id||result.id;media.push({id,media_type:context.mediaType||"image",metadata:{title:label}});select.append(el("option",{value:id,text:`${label} · ${String(id).slice(0,8)}`,selected:true}));select.value=id;state[key]=id;file.value="";ctx.shell.toast(`${label}: upload zakończony.`,"success");}catch(error){ctx.shell.toast(error.message,"error");}finally{upload.disabled=false;}}});
  return field(label,el("div",{class:"grid mediaPicker"},[select,file,el("div",{class:"actions"},[upload]),el("p",{class:"help",text:"Upload korzysta z centralnego Media Service i trafia do platform-media/site/."})]));
}
function listEditor(items, config, refresh) {
  const root=el("div",{class:"grid full"});
  const render=()=>{root.replaceChildren(...items.map((item,index)=>el("article",{class:"entityCard"},[
    el("div",{class:"formGrid"},config.fields(item,index)),
    el("div",{class:"actions"},[button("↑",{class:"small",disabled:index===0,onClick:()=>{[items[index-1],items[index]]=[items[index],items[index-1]];render();refresh?.();}}),button("↓",{class:"small",disabled:index===items.length-1,onClick:()=>{[items[index+1],items[index]]=[items[index],items[index+1]];render();refresh?.();}}),button("Usuń",{class:"small danger",onClick:()=>{items.splice(index,1);render();refresh?.();}})])
  ])),button(config.addLabel||"Dodaj",{onClick:()=>{items.push(config.create(items.length));render();refresh?.();}}));}; render(); return root;
}
function sectionFields(ctx,section,refresh,media){const c=section.content||{};const fields=[];
  if(section.type==="hero")fields.push(
    inputRow("Nadtytuł",c.eyebrow,v=>setContent(section,"eyebrow",v)),inputRow("Tytuł",c.title,v=>setContent(section,"title",v)),inputRow("Podtytuł",c.subtitle,v=>setContent(section,"subtitle",v)),inputRow("Opis",c.description,v=>setContent(section,"description",v),{multiline:true,full:true}),
    mediaField(ctx,c,media,"Logo Hero","logoMediaId",{category:"homepage/hero/logo",usageRole:"hero-logo"}),mediaField(ctx,c,media,"Obraz desktop","desktopMediaId",{category:"homepage/hero/desktop",usageRole:"hero-desktop"}),mediaField(ctx,c,media,"Obraz mobile","mobileMediaId",{category:"homepage/hero/mobile",usageRole:"hero-mobile"}),mediaField(ctx,c,media,"Film Hero","videoMediaId",{category:"homepage/hero/video",usageRole:"hero-video",accept:"video/*",mediaType:"video"}),
    inputRow("Primary CTA",c.primaryLabel,v=>setContent(section,"primaryLabel",v)),inputRow("Primary URL",c.primaryUrl,v=>setContent(section,"primaryUrl",v)),inputRow("Secondary CTA",c.secondaryLabel,v=>setContent(section,"secondaryLabel",v)),inputRow("Secondary URL",c.secondaryUrl,v=>setContent(section,"secondaryUrl",v)),
    (()=>{const s=selectInput("alignment",[{value:"left",label:"Lewa"},{value:"center",label:"Środek"},{value:"right",label:"Prawa"}],c.alignment||"left");s.onchange=()=>setContent(section,"alignment",s.value);return field("Wyrównanie",s);})(),inputRow("Kolor akcentu",c.theme?.accent||"",v=>{c.theme||={};c.theme.accent=v;},{type:"color"})
  );
  else if(section.type==="exhibition_collection"){const mode=selectInput("mode",[{value:"automatic",label:"Wszystkie opublikowane"},{value:"manual",label:"Wybrane ID"}],c.mode||"automatic");mode.onchange=()=>{c.mode=mode.value;refresh();};const layout=selectInput("layout",["carousel","grid","list"],c.layout||"carousel");layout.onchange=()=>c.layout=layout.value;const mobile=selectInput("mobileLayout",["carousel","grid","list"],c.mobileLayout||"carousel");mobile.onchange=()=>c.mobileLayout=mobile.value;fields.push(inputRow("Tytuł",c.title,v=>c.title=v),inputRow("Opis",c.description,v=>c.description=v,{multiline:true,full:true}),field("Wybór",mode),field("Desktop",layout),field("Mobile",mobile),inputRow("Widoczne karty",c.visibleCards||3,v=>c.visibleCards=Math.max(1,Math.min(8,v)),{type:"number"}));if(c.mode==="manual")fields.push(inputRow("Exhibition IDs",(c.exhibitionIds||[]).join("\n"),v=>c.exhibitionIds=String(v).split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean),{multiline:true,full:true}));}
  else if(section.type==="about")fields.push(inputRow("Tytuł",c.title,v=>c.title=v),inputRow("Opis",c.description,v=>c.description=v,{multiline:true,full:true}),inputRow("CTA",c.ctaLabel,v=>c.ctaLabel=v),inputRow("CTA URL",c.ctaUrl,v=>c.ctaUrl=v),listEditor(c.imageMediaIds||=([]),{addLabel:"Dodaj zdjęcie",create:()=>"",fields:(id,index)=>[mediaField(ctx,{get image(){return c.imageMediaIds[index]},set image(v){c.imageMediaIds[index]=v}},media,`Zdjęcie ${index+1}`,"image",{category:"homepage/about",usageRole:"about-image"})]},refresh));
  else if(section.type==="partners")fields.push(inputRow("Tytuł",c.title,v=>c.title=v),inputRow("Opis",c.description,v=>c.description=v,{multiline:true,full:true}),listEditor(c.items||=([]),{addLabel:"Dodaj partnera",create:index=>({id:`partner-${Date.now()}-${index}`,name:"",logoMediaId:null,url:"",altText:"",displayOrder:index*10}),fields:(item,index)=>[inputRow("Nazwa",item.name,v=>item.name=v),inputRow("Link",item.url,v=>item.url=v),inputRow("Alt text",item.altText,v=>item.altText=v),mediaField(ctx,item,media,"Logo partnera","logoMediaId",{category:`partners/${item.id}`,usageRole:"partner-logo",mediaType:"logo"})]},refresh));
  else if(section.type==="contact")fields.push(inputRow("Tytuł",c.title,v=>c.title=v),inputRow("Opis",c.description,v=>c.description=v,{multiline:true,full:true}),inputRow("Adres",c.address,v=>c.address=v,{multiline:true}),inputRow("E-mail",c.email,v=>c.email=v,{type:"email"}),inputRow("Telefon",c.phone,v=>c.phone=v),inputRow("Godziny",c.hours,v=>c.hours=v,{multiline:true}),inputRow("Mapa URL",c.mapUrl,v=>c.mapUrl=v),listEditor(c.socialLinks||=([]),{addLabel:"Dodaj social media",create:()=>({platform:"",label:"",url:""}),fields:item=>[inputRow("Platforma",item.platform,v=>item.platform=v),inputRow("Etykieta",item.label,v=>item.label=v),inputRow("URL",item.url,v=>item.url=v)]},refresh));
  else if(section.type==="footer")fields.push(mediaField(ctx,c,media,"Logo stopki","logoMediaId",{category:"footer/logo",usageRole:"footer-logo",mediaType:"logo"}),inputRow("Tekst",c.text,v=>c.text=v,{multiline:true,full:true}),inputRow("Copyright",c.copyright,v=>c.copyright=v),listEditor(c.links||=([]),{addLabel:"Dodaj link",create:()=>({label:"",url:""}),fields:item=>[inputRow("Etykieta",item.label,v=>item.label=v),inputRow("URL",item.url,v=>item.url=v)]},refresh),listEditor(c.socialLinks||=([]),{addLabel:"Dodaj social media",create:()=>({platform:"",label:"",url:""}),fields:item=>[inputRow("Platforma",item.platform,v=>item.platform=v),inputRow("Etykieta",item.label,v=>item.label=v),inputRow("URL",item.url,v=>item.url=v)]},refresh));
  return fields;
}
function sectionEditor(ctx,state,section,index,refresh,media){const enabled=el("input",{type:"checkbox",checked:section.enabled!==false});enabled.onchange=()=>section.enabled=enabled.checked;const order=textInput("displayOrder",section.displayOrder||((index+1)*10),{type:"number"});order.oninput=()=>section.displayOrder=Number(order.value||0);const actions=[button("↑",{class:"small",disabled:index===0,onClick:()=>{[state.sections[index-1],state.sections[index]]=[state.sections[index],state.sections[index-1]];refresh();}}),button("↓",{class:"small",disabled:index===state.sections.length-1,onClick:()=>{[state.sections[index+1],state.sections[index]]=[state.sections[index],state.sections[index+1]];refresh();}})];if(!["hero","exhibition_collection"].includes(section.type))actions.push(button("Usuń",{class:"small danger",onClick:()=>{state.sections.splice(index,1);refresh();}}));return el("article",{class:"entityCard sectionEditor"},[el("div",{class:"panelHeader"},[el("div",{},[el("strong",{text:LABELS[section.type]||section.type}),el("div",{class:"help",text:section.id})]),el("div",{class:"actions"},actions)]),el("div",{class:"formGrid"},[field("Widoczna",el("label",{class:"toggleField"},[enabled," Włączona"])),field("Kolejność",order),...sectionFields(ctx,section,refresh,media)])]);}
function defaultSection(type,index){const content={about:{title:"O galerii",description:"",imageMediaIds:[],ctaLabel:"",ctaUrl:""},partners:{title:"Partnerzy",description:"",items:[]},contact:{title:"Kontakt",description:"",address:"",email:"",phone:"",hours:"",mapUrl:"",socialLinks:[]},footer:{logoMediaId:null,text:"",copyright:"Berryboy Art Gallery",links:[],socialLinks:[],columns:[]}}[type]||{};return{id:`${type}-${Date.now()}`,type,enabled:true,displayOrder:(index+1)*10,content};}
function homepageEditor(ctx,value,media){const state=clone(normalizeHomepage(value));const root=el("div",{class:"grid"});const list=el("div",{class:"grid"});const refresh=()=>list.replaceChildren(...state.sections.map((section,index)=>sectionEditor(ctx,state,section,index,refresh,media)));const addType=selectInput("sectionType",["about","partners","contact","footer"].map(type=>({value:type,label:LABELS[type]})));const advanced=el("details",{class:"advancedEditor"},[el("summary",{text:"Advanced Developer View / import JSON"}),el("p",{class:"help",text:"Awaryjna ścieżka Platform Admin. Główna edycja odbywa się przez kontrolowane sekcje."}),(()=>{const area=jsonTextarea("advancedHomepage",state);return el("div",{class:"grid"},[area,el("div",{class:"actions"},[button("Zastosuj JSON",{onClick:()=>{const parsed=normalizeHomepage(parseJsonTextarea(area,"Homepage JSON"));state.sections.splice(0,state.sections.length,...parsed.sections);refresh();}}),button("Odśwież JSON",{onClick:()=>area.value=JSON.stringify(normalizeHomepage(state),null,2)})])]);})()]);root.append(list,el("div",{class:"actions"},[addType,button("Dodaj sekcję",{onClick:()=>{state.sections.push(defaultSection(addType.value,state.sections.length));refresh();}})]),advanced);refresh();return{node:root,getValue:()=>normalizeHomepage(state)};}
function settingsEditor(value){const state=normalizeSiteSettings(value||createDefaultSiteSettings());const form=el("div",{class:"formGrid"});form.append(inputRow("Nazwa strony",state.siteName,v=>state.siteName=v),field("Domyślny język",(()=>{const s=selectInput("locale",["pl","en"],state.defaultLocale);s.onchange=()=>state.defaultLocale=s.value;return s;})()),inputRow("E-mail",state.contactEmail,v=>state.contactEmail=v,{type:"email"}),inputRow("Telefon",state.contactPhone,v=>state.contactPhone=v),inputRow("Adres",state.address,v=>state.address=v,{multiline:true}),inputRow("Notatka stopki",state.footerNote,v=>state.footerNote=v,{multiline:true,full:true}),listEditor(state.socialLinks,{addLabel:"Dodaj social media",create:()=>({platform:"",label:"",url:""}),fields:item=>[inputRow("Platforma",item.platform,v=>item.platform=v),inputRow("Etykieta",item.label,v=>item.label=v),inputRow("URL",item.url,v=>item.url=v)]}),listEditor(state.legalLinks,{addLabel:"Dodaj link prawny",create:()=>({label:"",url:""}),fields:item=>[inputRow("Etykieta",item.label,v=>item.label=v),inputRow("URL",item.url,v=>item.url=v)]}));return{node:form,getValue:()=>normalizeSiteSettings(state)};}
function previewHomepage(value){return el("div",{class:"grid"},normalizeHomepage(value).sections.filter(s=>s.enabled).map(s=>el("article",{class:"entityCard"},[el("div",{class:"metaRow",text:`${s.displayOrder} · ${LABELS[s.type]||s.type}`}),el("h3",{text:s.content.title||s.content.copyright||s.id}),el("p",{text:s.content.description||s.content.text||""})])));}
export async function renderHomepage(ctx,route,key="homepage"){ctx.shell.setHeader(key==="homepage"?"homepage":"settings",key==="homepage"?"Homepage":"Site Settings");ctx.shell.loading();try{const[recordValue,media]=await Promise.all([ctx.repos.site.getEditor(key),key==="homepage"?ctx.repos.media.list():Promise.resolve([])]);const record=recordValue||{};const fallback=key==="homepage"?createDefaultHomepage():createDefaultSiteSettings();const value=record.draft_value||record.published_value||fallback;const editor=key==="homepage"?homepageEditor(ctx,value,media):settingsEditor(value);const validationRoot=el("div");const validate=()=>{try{const current=editor.getValue();const validation=key==="homepage"?validateHomepage(current):{valid:true,errors:[],value:normalizeSiteSettings(current)};validationRoot.replaceChildren(validation.valid?el("p",{class:"help",text:"Draft jest poprawny."}):el("ul",{class:"validationList error"},validation.errors.map(item=>el("li",{text:item}))));return validation;}catch(error){validationRoot.replaceChildren(el("p",{class:"formError",text:error.message}));return{valid:false,errors:[error.message]};}};validate();const actions=[actionButton("Podgląd draftu",async()=>{const v=validate();if(v.valid)ctx.shell.openDialog("Podgląd",previewHomepage(v.value));}),actionButton("Zapisz draft",async()=>{const v=validate();if(!v.valid)throw new Error(v.errors.join("; "));await attachSiteMedia(ctx,key,v.value);await ctx.repos.site.saveDraft(key,v.value,record.draft_revision,record.lock_version);await ctx.repos.media.finalizePending({ownerType:"site",ownerId:"site"});ctx.shell.toast("Draft i media zapisane.","success");await renderHomepage(ctx,route,key);},{class:"primary",disabled:!ctx.permissions.has("site.edit")}),actionButton("Opublikuj",async()=>{const v=validate();if(!v.valid)throw new Error(v.errors.join("; "));await ctx.repos.site.publish(key,record.draft_revision,record.lock_version);ctx.shell.toast("Treść została opublikowana atomowo.","success");await renderHomepage(ctx,route,key);},{disabled:!ctx.permissions.has("site.publish")}),actionButton("Rollback",async()=>{await ctx.repos.site.rollback(key);ctx.shell.toast("Przywrócono poprzednią publikację.","success");await renderHomepage(ctx,route,key);},{disabled:!ctx.permissions.has("site.publish")||!record.previous_value})];ctx.shell.view.replaceChildren(pageHead(key==="homepage"?"Homepage":"Site Settings",key==="homepage"?"Kontrolowany renderer publiczny, media strony i publikacja.":"Globalne ustawienia platformy."),panel(key==="homepage"?"Sekcje strony":"Ustawienia",el("div",{class:"grid"},[editor.node,validationRoot]),actions),panel("Stan wersji",el("div",{class:"metaRow"},[`Draft r${record.draft_revision||0}`,`Published r${record.published_revision||0}`,`Previous r${record.previous_revision||0}`,`Lock ${record.lock_version||0}`])));}catch(error){ctx.shell.view.replaceChildren(pageHead("Homepage","Treść strony publicznej."),errorBlock(error));}}
export function renderSettings(ctx,route){return renderHomepage(ctx,route,"site-settings");}
