import { el, button, statusBadge, field, textInput, selectInput, formValues, jsonTextarea, parseJsonTextarea, formatDate } from "../core/dom.js";
import { pageHead, panel, empty, errorBlock, actionButton } from "./shared.js";
import { slugify } from "../../src/platform/schemas/cms-schemas.js";

const ROLES=["building","walls","floor","ceiling","props","collision","navigation","decorations","texture","preview","manifest"];
const clone=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value||{}));
const num=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const vec=value=>({x:num(value?.x),y:num(value?.y),z:num(value?.z)});
function inputRow(label,value,onInput,options={}){const input=textInput(options.name||"field",value??"",{type:options.type||"text",multiline:options.multiline,class:options.full?"full":"",attrs:options.attrs||{}});input.addEventListener("input",()=>onInput(options.type==="number"?num(input.value):input.value));return field(label,input);}
function boolField(label,value,onChange){const input=el("input",{type:"checkbox",checked:!!value});input.onchange=()=>onChange(input.checked);return field(label,el("label",{class:"checkRow"},[input,el("span",{text:label})]));}
function vectorFields(label,target){target=target||={x:0,y:0,z:0};return el("fieldset",{class:"entityCard full"},[el("legend",{text:label}),el("div",{class:"formGrid"},[inputRow("X",target.x,v=>target.x=v,{type:"number"}),inputRow("Y",target.y,v=>target.y=v,{type:"number"}),inputRow("Z",target.z,v=>target.z=v,{type:"number"})])]);}
function listEditor(items,{label,create,fields}){const root=el("div",{class:"grid full"});const render=()=>{root.replaceChildren(...items.map((item,index)=>el("article",{class:"entityCard"},[el("div",{class:"panelHeader"},[el("strong",{text:`${label} ${index+1}`}),el("div",{class:"actions"},[button("↑",{class:"small",disabled:index===0,onClick:()=>{[items[index-1],items[index]]=[items[index],items[index-1]];render();}}),button("↓",{class:"small",disabled:index===items.length-1,onClick:()=>{[items[index+1],items[index]]=[items[index],items[index+1]];render();}}),button("Usuń",{class:"small danger",onClick:()=>{items.splice(index,1);render();}})])]),el("div",{class:"formGrid"},fields(item,index))])),button(`Dodaj: ${label}`,{onClick:()=>{items.push(create(items.length));render();}}));};render();return root;}
function venueCreateForm(ctx){const form=el("form",{class:"formGrid"});const name=textInput("name","",{required:true});const slug=textInput("slug","",{required:true});name.oninput=()=>{if(!slug.dataset.manual)slug.value=slugify(name.value);};slug.oninput=()=>slug.dataset.manual="1";form.append(field("Nazwa Venue",name),field("Slug",slug),field("Opis",textInput("description","",{multiline:true,class:"full"})),el("div",{class:"actions full"},[button("Utwórz Venue",{class:"primary",type:"submit"})]));form.onsubmit=async event=>{event.preventDefault();try{const created=await ctx.repos.venues.create(formValues(form));ctx.shell.toast("Venue zostało utworzone.","success");ctx.router.navigate("venues",created.id||created.venue_id);}catch(error){ctx.shell.toast(error.message,"error");}};return form;}
function createVersionForm(ctx,venue){const form=el("form",{class:"formGrid"});const version=textInput("versionNumber","v1",{required:true});form.append(field("Numer wersji",version),el("div",{class:"actions"},[button("Utwórz wersję",{class:"primary",type:"submit"})]));form.onsubmit=async event=>{event.preventDefault();try{const result=await ctx.repos.venues.createVersion(venue.id,version.value);ctx.shell.toast("Wersja Venue została utworzona.","success");await renderVenueDetail(ctx,venue.id,result.id||result.venue_version_id);}catch(error){ctx.shell.toast(error.message,"error");}};return form;}
function assetUploadForm(ctx,venue,version,onDone){const form=el("form",{class:"formGrid"});const assetId=textInput("assetId","",{required:true,placeholder:"main-building"});const role=selectInput("role",ROLES);const file=el("input",{type:"file",name:"file",required:true,attrs:{accept:".glb,.gltf,.json,.png,.jpg,.jpeg,.webp,.avif,application/octet-stream,model/gltf-binary"}});form.append(field("Asset ID",assetId),field("Rola",role),field("Plik",file),el("div",{class:"actions"},[button("Wgraj asset",{class:"primary",type:"submit"})]));form.onsubmit=async event=>{event.preventDefault();try{await ctx.repos.venues.uploadAsset({venue,version,assetId:assetId.value,role:role.value,file:file.files[0]});ctx.shell.toast("Asset przeszedł centralny lifecycle i został zarejestrowany.","success");form.reset();await onDone();}catch(error){ctx.shell.toast(error.message,"error");}};return form;}

function manifestEditor(manifestValue,venue,version){const manifest=clone(manifestValue||{});manifest.schema||="berryboy-venue-manifest.v1";manifest.venueId||=venue.slug||venue.id;manifest.versionId||=version.version_number;manifest.coordinateSystem||={upAxis:"Y",units:"meters"};manifest.assets||=[];manifest.spawnPoints||=[];manifest.zones||=[];manifest.zoneAdjacency||=[];manifest.collisionSets||=[];manifest.walkableAreas||=[];manifest.artworkAnchors||=[];manifest.sculptureAnchors||=[];manifest.navigationGraph||={nodes:[],edges:[]};manifest.editableMaterials||=[];manifest.lockedMaterials||=[];manifest.lightingDefaults||={};manifest.mobileBudgets||={};manifest.technicalFlags||={};
 const root=el("div",{class:"grid"});
 const general=el("div",{class:"formGrid"},[inputRow("Schema",manifest.schema,v=>manifest.schema=v),inputRow("Venue ID",manifest.venueId,v=>manifest.venueId=v),inputRow("Version ID",manifest.versionId,v=>manifest.versionId=v),field("Jednostki",(()=>{const s=selectInput("units",["meters","centimeters","millimeters"],manifest.coordinateSystem.units||"meters");s.onchange=()=>manifest.coordinateSystem.units=s.value;return s;})()),field("Up axis",(()=>{const s=selectInput("axis",["Y","Z"],manifest.coordinateSystem.upAxis||"Y");s.onchange=()=>manifest.coordinateSystem.upAxis=s.value;return s;})())]);
 const spawn=listEditor(manifest.spawnPoints,{label:"Spawn point",create:index=>({id:`spawn-${index+1}`,position:{x:0,y:0,z:0},target:{x:0,y:0,z:1},safe:false,visitor:false,editor:false,floorLevel:0}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Floor level",item.floorLevel||0,v=>item.floorLevel=v,{type:"number"}),vectorFields("Pozycja",item.position||=(vec())),vectorFields("Target",item.target||=(vec({z:1}))),boolField("Viewer spawn",item.visitor,v=>item.visitor=v),boolField("Editor spawn",item.editor,v=>item.editor=v),boolField("Safe spawn",item.safe,v=>item.safe=v)]});
 const zones=listEditor(manifest.zones,{label:"Zone",create:index=>({id:`zone-${index+1}`,name:"",bounds:{min:{x:0,y:0,z:0},max:{x:1,y:1,z:1}},streamingPriority:0,assetIds:[]}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Nazwa",item.name||"",v=>item.name=v),inputRow("Streaming priority",item.streamingPriority||0,v=>item.streamingPriority=v,{type:"number"}),inputRow("Asset IDs (przecinki)",(item.assetIds||[]).join(", "),v=>item.assetIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),vectorFields("Bounds min",(item.bounds ||= {min:vec(),max:vec({x:1,y:1,z:1})}).min),vectorFields("Bounds max",item.bounds.max)]});
 const adjacency=listEditor(manifest.zoneAdjacency,{label:"Połączenie stref",create:()=>({from:"",to:"",bidirectional:true,cost:1}),fields:item=>[inputRow("From",item.from,v=>item.from=v),inputRow("To",item.to,v=>item.to=v),inputRow("Cost",item.cost||1,v=>item.cost=v,{type:"number"}),boolField("Dwukierunkowe",item.bidirectional!==false,v=>item.bidirectional=v)]});
 const collisions=listEditor(manifest.collisionSets,{label:"Collision set",create:index=>({id:`collision-${index+1}`,assetIds:[],meshIds:[],type:"blocking",enabled:true,viewer:true,editor:true}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),field("Typ",(()=>{const s=selectInput("type",["blocking","walkable","trigger"],item.type||"blocking");s.onchange=()=>item.type=s.value;return s;})()),inputRow("Asset IDs",(item.assetIds||[]).join(", "),v=>item.assetIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),inputRow("Mesh IDs",(item.meshIds||[]).join(", "),v=>item.meshIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),boolField("Aktywne",item.enabled!==false,v=>item.enabled=v),boolField("Viewer",item.viewer!==false,v=>item.viewer=v),boolField("Editor",item.editor!==false,v=>item.editor=v)]});
 const walkable=listEditor(manifest.walkableAreas,{label:"Walkable area",create:index=>({id:`walkable-${index+1}`,zoneId:"",assetIds:[],meshIds:[],enabled:true}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Zone ID",item.zoneId||"",v=>item.zoneId=v),inputRow("Asset IDs",(item.assetIds||[]).join(", "),v=>item.assetIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),inputRow("Mesh IDs",(item.meshIds||[]).join(", "),v=>item.meshIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),boolField("Aktywne",item.enabled!==false,v=>item.enabled=v)]});
 const anchorEditor=(items,label)=>listEditor(items,{label,create:index=>({id:`${label.toLowerCase().replace(/\s/g,"-")}-${index+1}`,zoneId:"",ownerSurfaceId:"",position:{x:0,y:0,z:0},normal:{x:0,y:0,z:1},maxWidth:2,maxHeight:2,maxDepth:2}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Zone ID",item.zoneId||"",v=>item.zoneId=v),inputRow("Owner surface",item.ownerSurfaceId||"",v=>item.ownerSurfaceId=v),inputRow("Max width",item.maxWidth||2,v=>item.maxWidth=v,{type:"number"}),inputRow("Max height",item.maxHeight||2,v=>item.maxHeight=v,{type:"number"}),inputRow("Max depth",item.maxDepth||2,v=>item.maxDepth=v,{type:"number"}),vectorFields("Pozycja",item.position||=(vec())),vectorFields("Normal / kierunek",item.normal||=(vec({z:1})))]});
 const navNodes=listEditor(manifest.navigationGraph.nodes,{label:"Navigation node",create:index=>({id:`node-${index+1}`,zoneId:"",position:{x:0,y:0,z:0}}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Zone ID",item.zoneId||"",v=>item.zoneId=v),vectorFields("Pozycja",item.position||=(vec()))]});
 const navEdges=listEditor(manifest.navigationGraph.edges,{label:"Navigation edge",create:()=>({from:"",to:"",cost:1,bidirectional:true}),fields:item=>[inputRow("From",item.from,v=>item.from=v),inputRow("To",item.to,v=>item.to=v),inputRow("Cost",item.cost||1,v=>item.cost=v,{type:"number"}),boolField("Dwukierunkowe",item.bidirectional!==false,v=>item.bidirectional=v)]});
 const materials=listEditor(manifest.editableMaterials,{label:"Editable material",create:index=>({id:`material-${index+1}`,meshIds:[],allowColor:true,allowReflection:false,defaultColor:"#ffffff"}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Mesh IDs",(item.meshIds||[]).join(", "),v=>item.meshIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),inputRow("Default color",item.defaultColor||"#ffffff",v=>item.defaultColor=v,{type:"color"}),boolField("Zmiana koloru",item.allowColor!==false,v=>item.allowColor=v),boolField("Zmiana odbić",item.allowReflection,v=>item.allowReflection=v)]});
 const locked=listEditor(manifest.lockedMaterials,{label:"Locked material",create:index=>({id:`locked-${index+1}`,meshIds:[],reason:""}),fields:item=>[inputRow("ID",item.id,v=>item.id=v),inputRow("Mesh IDs",(item.meshIds||[]).join(", "),v=>item.meshIds=String(v).split(",").map(x=>x.trim()).filter(Boolean),{full:true}),inputRow("Powód blokady",item.reason||"",v=>item.reason=v,{full:true})]});
 const lighting=el("div",{class:"formGrid"},[inputRow("Environment URL",manifest.lightingDefaults.environmentTextureUrl||"",v=>manifest.lightingDefaults.environmentTextureUrl=v,{full:true}),inputRow("Environment intensity",manifest.lightingDefaults.environmentIntensity??0.35,v=>manifest.lightingDefaults.environmentIntensity=v,{type:"number"}),inputRow("Exposure",manifest.lightingDefaults.exposure??1,v=>manifest.lightingDefaults.exposure=v,{type:"number"}),inputRow("Contrast",manifest.lightingDefaults.contrast??1,v=>manifest.lightingDefaults.contrast=v,{type:"number"}),inputRow("Permanent lights JSON",JSON.stringify(manifest.lightingDefaults.permanentLights||[],null,2),v=>{try{manifest.lightingDefaults.permanentLights=JSON.parse(v||"[]");}catch{}},{multiline:true,full:true})]);
 const mobile=el("div",{class:"formGrid"},[inputRow("Max models",manifest.mobileBudgets.maxModels||0,v=>manifest.mobileBudgets.maxModels=v,{type:"number"}),inputRow("Max texture MB",manifest.mobileBudgets.maxTextureMemoryMb||0,v=>manifest.mobileBudgets.maxTextureMemoryMb=v,{type:"number"}),inputRow("Full artwork limit",manifest.mobileBudgets.fullArtworkLimit||0,v=>manifest.mobileBudgets.fullArtworkLimit=v,{type:"number"}),boolField("Dziedzicz C6C2",manifest.mobileBudgets.inheritCanonicalC6C2!==false,v=>manifest.mobileBudgets.inheritCanonicalC6C2=v),boolField("DBG C6C2 aktywny",manifest.technicalFlags.mobileC6C2DiagnosticsActive!==false,v=>manifest.technicalFlags.mobileC6C2DiagnosticsActive=v)]);
 const advancedArea=jsonTextarea("advancedManifest",manifest);const advanced=el("details",{class:"advancedEditor"},[el("summary",{text:"Advanced Developer View / import-export manifestu"}),el("p",{class:"help",text:"Raw JSON nie jest głównym edytorem. Używaj go wyłącznie do importu, eksportu i awaryjnej diagnostyki Platform Admin."}),advancedArea,el("div",{class:"actions"},[button("Zastosuj JSON",{onClick:()=>{const parsed=parseJsonTextarea(advancedArea,"Venue Manifest");Object.keys(manifest).forEach(key=>delete manifest[key]);Object.assign(manifest,parsed);advancedArea.value=JSON.stringify(manifest,null,2);}}),button("Odśwież JSON",{onClick:()=>advancedArea.value=JSON.stringify(manifest,null,2)})])]);
 const sections=[["GENERAL",general],["SPAWN POINTS",spawn],["ZONES",el("div",{class:"grid"},[zones,adjacency])],["COLLISIONS & WALKABLE",el("div",{class:"grid"},[collisions,walkable])],["ARTWORK ANCHORS",anchorEditor(manifest.artworkAnchors,"Artwork anchor")],["SCULPTURE ANCHORS",anchorEditor(manifest.sculptureAnchors,"Sculpture anchor")],["NAVIGATION",el("div",{class:"grid"},[navNodes,navEdges])],["MATERIALS",el("div",{class:"grid"},[materials,locked])],["LIGHTING",lighting],["MOBILE",mobile]];
 sections.forEach(([title,node])=>root.append(panel(title,node)));root.append(advanced);return{node:root,getValue:()=>clone(manifest)};}

async function renderVenueDetail(ctx,venueId,preferredVersionId=null){ctx.shell.setHeader("venues","Venue","Site Admin / Venues");ctx.shell.loading();try{const detail=await ctx.repos.venues.get(venueId);const venue=detail.venue||detail;const versions=Array.isArray(detail.versions)?detail.versions:[];const version=versions.find(item=>item.id===preferredVersionId)||versions.find(item=>item.id===venue.draft_version_id)||versions[0]||null;const canEdit=ctx.permissions.canVenue("venue.edit",venue.id);const canPublish=ctx.permissions.canVenue("venue.publish",venue.id);const topActions=[button("← Lista",{onClick:()=>ctx.router.navigate("venues")})];if(canEdit)topActions.push(actionButton("Archiwizuj",async()=>{if(!await ctx.shell.confirmAction("Venue zostanie ukryte i przeniesione do archiwum.","Archiwizuj"))return;await ctx.repos.venues.archive(venue.id);ctx.shell.toast("Venue zarchiwizowane.","success");ctx.router.navigate("venues");},{class:"danger"}));
 const infoForm=el("form",{class:"formGrid"});infoForm.append(field("Nazwa",textInput("name",venue.name,{required:true})),field("Slug",textInput("slug",venue.slug,{required:true})),field("Opis",textInput("description",venue.description||"",{multiline:true,class:"full"})),el("div",{class:"actions full"},[button("Zapisz dane Venue",{class:"primary",type:"submit",disabled:!canEdit})]));infoForm.onsubmit=async event=>{event.preventDefault();try{await ctx.repos.venues.update(venue.id,formValues(infoForm));ctx.shell.toast("Dane Venue zapisane.","success");await renderVenueDetail(ctx,venue.id,version?.id);}catch(error){ctx.shell.toast(error.message,"error");}};
 const versionCards=versions.length?el("div",{class:"cardList"},versions.map(item=>el("article",{class:"entityCard"},[el("div",{class:"metaRow"},[statusBadge(item.status),formatDate(item.created_at)]),el("h3",{text:item.version_number}),el("p",{text:`${item.asset_count||0} assetów`}),button("Otwórz wersję",{class:item.id===version?.id?"primary":"",onClick:()=>renderVenueDetail(ctx,venue.id,item.id)})]))):empty("To Venue nie ma jeszcze wersji.");
 let versionPanel=empty("Utwórz pierwszą wersję Venue.");if(version){const editor=manifestEditor(version.manifest||{},venue,version);const validation=version.validation_report||{};const manifestActions=[actionButton("Zapisz manifest",async()=>{await ctx.repos.venues.saveManifest(version.id,editor.getValue());ctx.shell.toast("Manifest zapisany.","success");await renderVenueDetail(ctx,venue.id,version.id);},{disabled:!canEdit||version.status==="published"}),actionButton("Waliduj",async()=>{const result=await ctx.repos.venues.validateVersion(version.id);ctx.shell.toast(result.valid?"Manifest jest poprawny.":"Manifest wymaga poprawek.",result.valid?"success":"error");await renderVenueDetail(ctx,venue.id,version.id);},{disabled:!canEdit}),actionButton("Test Venue",async()=>{const url=new URL("../gallery/",location.href);url.searchParams.set("venueTestVersionId",version.id);url.searchParams.set("returnUrl",`${location.pathname}${location.hash||`#venues/${venue.id}?version=${version.id}`}`);window.open(url.href,"_blank","noopener");}),actionButton("Opublikuj wersję",async()=>{await ctx.repos.venues.publishVersion(version.id);ctx.shell.toast("Wersja Venue opublikowana.","success");await renderVenueDetail(ctx,venue.id,version.id);},{class:"primary",disabled:!canPublish||version.status==="published"})];const assets=Array.isArray(version.assets)?version.assets:[];versionPanel=el("div",{class:"grid"},[panel(`Kontrolowany Venue Editor — ${version.version_number}`,el("div",{class:"grid"},[editor.node,validation.errors?.length?el("ul",{class:"validationList error"},validation.errors.map(message=>el("li",{text:message}))):null,validation.warnings?.length?el("ul",{class:"validationList warning"},validation.warnings.map(message=>el("li",{text:message}))):null]),manifestActions),panel("ASSETS",assets.length?el("div",{class:"tableWrap"},[el("table",{},[el("thead",{},el("tr",{},["Asset ID","Rola","Plik","Rozmiar","Hash"].map(value=>el("th",{text:value})))),el("tbody",{},assets.map(asset=>el("tr",{},[el("td",{text:asset.asset_id}),el("td",{},statusBadge(asset.role)),el("td",{text:asset.storage_path||asset.public_url||"—"}),el("td",{text:asset.file_size||"—"}),el("td",{text:asset.file_hash?String(asset.file_hash).slice(0,12):"—"})])) )])]):empty("Brak assetów.")),canEdit&&version.status!=="published"?panel("UPLOAD ASSET",assetUploadForm(ctx,venue,version,()=>renderVenueDetail(ctx,venue.id,version.id))):null]);}
 ctx.shell.view.replaceChildren(pageHead(venue.name,`${venue.slug} · ${venue.status}`,topActions),el("div",{class:"grid twoColumn"},[el("div",{class:"grid"},[panel("GENERAL",infoForm),panel("Wersje",versionCards)]),panel("Nowa wersja",createVersionForm(ctx,venue))]),versionPanel);}catch(error){ctx.shell.view.replaceChildren(pageHead("Venue","Szczegóły Venue."),errorBlock(error));}}
export async function renderVenues(ctx,route){if(route.id)return renderVenueDetail(ctx,route.id,route.params.get("version"));ctx.shell.setHeader("venues","Venues");ctx.shell.loading();try{const venues=await ctx.repos.venues.list();const create=ctx.permissions.has("venue.create")?button("Dodaj Venue",{class:"primary",onClick:()=>ctx.shell.openDialog("Nowe Venue",venueCreateForm(ctx))}):null;const cards=venues.length?el("div",{class:"cardList"},venues.map(venue=>el("article",{class:"entityCard"},[el("div",{class:"metaRow"},[statusBadge(venue.status),`${venue.version_count||0} wersji`,`${venue.exhibition_count||0} wystaw`]),el("h3",{text:venue.name}),el("p",{text:venue.description||venue.slug}),button("Zarządzaj",{onClick:()=>ctx.router.navigate("venues",venue.id)})]))):empty("Brak dostępnych Venue.");ctx.shell.view.replaceChildren(pageHead("Venues","Budynki, wersje modeli, manifesty i kontrolowane ustawienia techniczne.",[create]),cards);}catch(error){ctx.shell.view.replaceChildren(pageHead("Venues","Budynki platformy."),errorBlock(error));}}
