import fs from 'node:fs';
import crypto from 'node:crypto';

const source=fs.readFileSync(new URL('../src/Gallery_V0_11.js',import.meta.url),'utf8');
const minified=fs.readFileSync(new URL('../src/Gallery_V0_11.min.js',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const bootstrap=fs.readFileSync(new URL('../src/bootstrap/gallery-viewer-bootstrap.js',import.meta.url),'utf8');
const editorBootstrap=fs.readFileSync(new URL('../src/bootstrap/gallery-editor-bootstrap.js',import.meta.url),'utf8');
const admin=fs.readFileSync(new URL('../admin.html',import.meta.url),'utf8');
const adminBootstrap=fs.readFileSync(new URL('../src/bootstrap/admin-workspace-bootstrap.js',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('../src/workers/gallery-avif-encoder-worker.js',import.meta.url),'utf8');
const adapter=fs.readFileSync(new URL('../src/vendor/gallery-avif-encoder.mjs',import.meta.url),'utf8');
const spaceConfig=fs.readFileSync(new URL('../src/config/gallery-space-config.js',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../SUPABASE_SQL/01_MULTI_EXHIBITION_CORE_STORAGE_POLICIES.sql',import.meta.url),'utf8');
const currentMigration=fs.readFileSync(new URL('../SUPABASE_SQL/04_RUNTIME_HYGIENE_PUBLICATION_POLICIES.sql',import.meta.url),'utf8');
const txt=fs.readFileSync(new URL('../ENGINE_LOGIN_DISABLED.txt',import.meta.url),'utf8');
const assetCacheBootstrap=fs.readFileSync(new URL('../src/bootstrap/asset-cache-bootstrap.js',import.meta.url),'utf8');
const assetCacheSw=fs.readFileSync(new URL('../asset-cache-sw.js',import.meta.url),'utf8');
const transitionGuard=fs.readFileSync(new URL('../src/bootstrap/transition-guard.js',import.meta.url),'utf8');

function assert(c,m){if(!c)throw new Error(m)}
function count(h,n){return h.split(n).length-1}
function sha(t){return crypto.createHash('sha256').update(t).digest('hex')}
function extractFunction(text,name){const ms=[`async function ${name}(`,`function ${name}(`];let st=-1;for(const m of ms){st=text.indexOf(m);if(st>=0)break}assert(st>=0,`Missing ${name}`);const b=text.indexOf('{',st);let d=0,s='c',q='';for(let i=b;i<text.length;i++){const c=text[i],n=text[i+1]||'';if(s==='c'){if(c==='"'||c==="'"||c==='`'){s='s';q=c}else if(c==='/'&&n==='/'){s='l';i++}else if(c==='/'&&n==='*'){s='b';i++}else if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(st,i+1)}else if(s==='s'){if(c==='\\')i++;else if(c===q)s='c'}else if(s==='l'&&c==='\n')s='c';else if(s==='b'&&c==='*'&&n==='/'){s='c';i++}}throw new Error(`Unterminated ${name}`)}

assert(index.includes('stage: "12C66C6C8C10"'),'Index stage identity missing');
assert(bootstrap.includes('const STAGE = "12C66C6C8C10"'),'Viewer stage identity missing');
assert(adminBootstrap.includes('const STAGE = "12C66C6C8C10"'),'Admin stage identity missing');
assert(bootstrap.includes('stage12c66c6c8c10_startup_critical_path_background_budget_20260813'),'Current cache key missing');
assert(index.includes('gallery-viewer-bootstrap.js?v=stage12c66c6c8c10_startup_critical_path_background_budget_20260813'),'Index cache key missing');
assert(source.includes('Stage 12C66C6C8C10: Startup Critical Path + Background Hydration Budget'),'Current source history missing');
assert(bootstrap.includes('adaptToDeviceRatio: false'),'Bootstrap still owns device DPR');
assert(sha(extractFunction(source,'createViewerIntroOverlayStyles'))==='93595efee4b7f720f32b5a8b739f6212bcea793ed8bdc88e939ea243b74262d6','Accepted intro CSS changed');
assert(sha(extractFunction(source,'showViewerIntroOverlay'))==='fb4b8f6a0b72653489b10564492ffad9f52ba461bf67cb1992bd21e655aaf537','Accepted intro behavior changed');
assert(count(source,'function resolveGalleryGroundMovement(')===1,'Unified collision resolver changed');
assert(!source.includes('.moveWithCollisions('),'Native collision path returned');
assert(source.includes('schema: "gallery-sculpture-core.v2"'),'Sculpture core missing');
assert(source.includes('schema: "gallery-artwork-runtime.v1"'),'Artwork runtime missing');
assert(source.includes('schema: "gallery-atomic-media-lifecycle.v1"'),'Atomic media lifecycle missing');
assert(source.includes('schema: "gallery-mobile-quality-domains.v2"'),'Mobile quality domains missing');
assert(source.includes('schema: "gallery-artwork-residency.v3"'),'Artwork residency missing');
assert(source.includes('REPAIR MEDIA')&&source.includes('AUDIT & CLEAN MEDIA'),'Media recovery controls missing');
assert(source.includes('var galleryAvifEncoderModuleUrl = "src/vendor/gallery-avif-encoder.mjs"'),'AVIF entrypoint missing');
assert(worker.includes('import(moduleUrl)')&&adapter.includes('ImageEncoder'),'AVIF worker/adapter missing');
assert(source.includes('function switchGalleryExhibition(')&&source.includes('function createGalleryExhibition('),'Multi-exhibition runtime missing');
assert(!source.includes('.eq("id", "main")'),'Hard-coded gallery_state main query remains');
assert(spaceConfig.includes('Floor_segment.glb')&&spaceConfig.includes('Wall_segments.glb')&&spaceConfig.includes('Ceiling.glb')&&spaceConfig.includes('Props.glb'),'Space assets missing');
assert(spaceConfig.includes('version: 1'),'Space asset versioning missing');
assert(migration.includes('create table if not exists public.gallery_exhibitions'),'Exhibition migration missing');
assert(currentMigration.includes('(storage.foldername(name))[2] = \'frames\''),'Shared frame public exception missing');
assert(admin.includes('id="adminViewportStage"')&&admin.includes('id="exhibitionList"'),'Direct Admin page missing');
assert(source.includes('enterAdminWorkspaceMode: enterGalleryAdminWorkspaceMode')&&source.includes('exitAdminWorkspaceMode: exitGalleryAdminWorkspaceMode'),'Same-runtime engine mode API missing');
assert(source.includes('discardUnsavedChanges: discardGalleryUnsavedChanges'),'Scene discard API missing');
assert(source.includes('function applyGallerySameSpaceExhibitionState(')&&source.includes('lastSwitchMode = "same-space-delta-load"')&&source.includes('lastSwitchMode = "resident-layer-resume"'),'Same-space Exhibition delta/resident path missing');
assert(source.includes('function refreshViewerExhibitionCollisionMeshes('),'Exhibition-only collision refresh missing');
assert(!source.includes('ensureGalleryExhibitTourCurrent("enter-edit-mode")')&&!source.includes('ensureGalleryExhibitTourCurrent("same-runtime-admin-enter")'),'Edit/Admin mode still rebuilds Tour unconditionally');
assert(bootstrap.includes('openInlineAdminWorkspace')&&bootstrap.includes('engine: activeEngine')&&bootstrap.includes('scene: activeScene'),'Viewer same-runtime handoff missing');
assert(adminBootstrap.includes('inlineRuntimeContext.engine')&&adminBootstrap.includes('inlineRuntimeContext.scene'),'Admin inline runtime reuse missing');
assert(adminBootstrap.includes('export async function suspendAdminWorkspace()'),'Admin suspend API missing');
assert(admin.includes('.adminButton:visited')&&admin.includes('text-decoration:none'),'Public Page button style fix missing');
assert(assetCacheBootstrap.includes('SERVICE_WORKER_URL')&&assetCacheSw.includes('exhibition-platform-assets-v1'),'Persistent asset cache missing');
assert(minified.includes('syncGalleryArtworkEgressPolicyForWorkspaceMode')&&minified.includes('gallery-artwork-residency.v3'),'Production runtime missing current hygiene changes');
assert(txt.includes('var galleryEditorLoginEnabled = false;')&&txt.includes('globalThis.BerryboyGallerySpaceDefinition ='),'Login-disabled test build missing');
assert(source.includes('function parkActiveGalleryExhibitionLayer(')&&source.includes('function restoreGalleryExhibitionLayer('),'Exhibition layer residency missing');
assert(source.includes('function setGallerySameRuntimeModeState(')&&source.includes('same-runtime-ui-only'),'Zero-reload mode transition missing');
assert(admin.includes('id="networkDiagnostics"')&&adminBootstrap.includes('getExhibitionAssetDeliveryStats'),'Admin network diagnostics missing');
assert(assetCacheSw.includes('EXHIBITION_ASSET_DELIVERY_STATS')&&assetCacheSw.includes('supabaseNetworkFetches'),'Storage delivery instrumentation missing');
assert(transitionGuard.includes('beginTransitionGuard')&&transitionGuard.includes('endTransitionGuard')&&transitionGuard.includes('epTransitionSpinner'),'Transition guard module missing');
assert(source.includes('function tagGallerySceneOwner(')&&source.includes('function verifyGalleryCanonicalSpaceIntegrity('),'C6C8C7 scene ownership/integrity guard missing');
assert(source.includes('galleryExhibitionRuntime.hydrationActive = true')&&source.includes('scheduleGalleryDeferredTourAfterHydration'),'C6C8C7 atomic hydration/deferred Tour missing');
assert(source.includes('blockedSpaceDisposals')&&source.includes('lastHydrationProfile'),'C6C8C7 diagnostics missing');
assert(transitionGuard.includes('setTimeout(resolve, 34)'),'C6C8C7 transition paint barrier missing');
assert(bootstrap.includes('Returning to Public Page…')&&bootstrap.includes('Opening Admin Workspace…'),'Viewer/Admin same-runtime transition feedback missing');
assert(adminBootstrap.includes('Switching to ${target.name}…')&&adminBootstrap.includes('Keeping the current 3D Space resident.'),'Exhibition switch loading feedback missing');
assert(adminBootstrap.includes('void captureExhibitionTransitionDiagnostic'),'Diagnostics still block the visible exhibition transition');
assert(source.includes('schema: "gallery-artwork-residency.v3"'),'C6C8C8 residency schema missing');
assert(source.includes('function isGalleryViewerTextureStreamingMotionBlocked('),'C6C8C8 movement gate missing');
assert(source.includes('desktopHardFullTextures: 8')&&source.includes('fullReentryCooldownMs: 18000'),'C6C8C8 hysteresis policy missing');
assert(source.includes('if (!entry || !entry.inspectPriority) return false;'),'Critical/visible movement bypass still active');
assert(source.includes('_galleryNoAutoFullQueue = true')&&source.includes('preview-auto-full-suppressed'),'Downgrade anti-thrash guard missing');
assert(adminBootstrap.includes('move-block')&&adminBootstrap.includes('thrash'),'C6C8C8 diagnostics missing');
assert(source.includes('function sweepGalleryInactiveExhibitionOwners(')&&source.includes('active-context-change'),'C6C8C9 owner-driven orphan sweep missing');
assert(source.includes('function waitForGalleryForegroundReady(')&&source.includes('function runGallerySpaceGpuWarmup('),'C6C8C9 true foreground readiness/GPU warmup missing');
assert(source.includes('PerformanceObserver')&&source.includes('entryTypes: ["longtask"]'),'C6C8C9 long-task observer missing');
assert(bootstrap.includes('waitForForegroundReady("admin-to-public"')&&bootstrap.includes('waitForForegroundReady("public-to-admin"'),'C6C8C9 Viewer/Admin guard readiness wait missing');
assert(adminBootstrap.includes('waitForForegroundReady(`switch:${fromId}->${id}`'),'C6C8C9 exhibition switch readiness wait missing');
assert(source.includes('function prepareGalleryForegroundArtworkBudget(')&&source.includes('foregroundArtworkLimit'),'C6C8C10 bounded foreground artwork budget missing');
assert(source.includes('function getGalleryBackgroundHydrationPauseReason(')&&source.includes('model-idle-budget'),'C6C8C10 motion-aware background budget missing');
assert(source.includes('gallerySpaceGpuWarmMaterialCache')&&source.includes('Promise.all(pairs.slice(i, i + batchSize)'),'C6C8C10 cached batched Space GPU warmup missing');
assert(adminBootstrap.includes('BG slices')&&adminBootstrap.includes('bounded foreground Preview set'),'C6C8C10 Admin background diagnostics missing');
console.log('Current Exhibition Platform verifier passed.');
